### ISSUE TITLE
Musicophile Achievement

### ISSUE THREAD

**Issue by eEeEeEe102** [hackclub/HCCore#109]
Im Bernardo from hackclub, and I found out that in the achievement in the title there are 2 bugs, 1 is that the first 12 music disks (not pigstep) does not grant you the achievement when you have all of the disks unless you got them from a creeper, the other bug is that if you got the achievement before 1.16.1 you still keep the achievement even do you dont have all the disks.

**Comment by lukec11** [comment]
>  if you got the achievement before 1.16.1 you still keep the achievement even do you dont have all the disks.

This isn't a problem - we aren't going to support retroactively removing achievements.

> does not grant you the achievement when you have all of the disks unless you got them from a creeper

The library we use (AdvancementCreator) doesn't use mob drops to check - it checks that you have had all of the items in your possession. As long as music disks have the same IDs (shown below) it should work fine.  If there's some reason it doesn't, let me know and I can look into it further. https://github.com/hackclub/HCCore/blob/7c6f2c68eb3317012f507c72cd8f755ccf50dcd1/src/main/java/com/hackclub/hccore/HCCorePlugin.java#L121-L127

**Comment by lukec11** [comment]
Going to close for inactivity - let me know if an issue does crop up here and we can look into it.
