### ISSUE TITLE
Move all sent messages into one file

### ISSUE THREAD

**Issue by ifvictr** [hackclub/HCCore#12]
Messages are currently hardcoded. It'd be nice to move everything into an enum at `com.hackclub.hccore.Language` or something. Then you'd call it by writing something like this:

```java
// Language.COMMAND_NOT_FOUND -> "This command doesn't exist"
player.sendMessage(Language.COMMAND_NOT_FOUND);
// With parameters
// Language.EVENT_PLAYER_JOINED -> "{displayName} joined the game"
player.sendMessage(Language.EVENT_PLAYER_JOINED.replace("{displayName}", player.getDisplayName()));
```

~And maybe the Language enum would read it from a `messages.yml` in the resources folder?~

**Comment by nice6599** [comment]
can you further explain what needs to be done here?
