### ISSUE TITLE
Auto deploying && Auto Deploying PR builds to testing server

### ISSUE THREAD

**Issue by alx-alexpark** [hackclub/HCCore#128]
Using github actions(preferred) or travis, the file needs to be sent to the plugins folder on the aws ec2 instance, and a script to restart the server needs to be executed.

There are 4 domains, with 2 of them having SRV records leading to `18.219.123.37`
modded-mc.hackclub.com (25566)
vmc.hackclub.com
beta-mc.hackclub.com (25567)
mc.hackclub.com

2 of those domains are unused, We could use beta-mc.hackclub.com for the testing server. Also we do have the compute resources to run the testing server.

**Comment by alx-alexpark** [comment]
Thanks @SConaway for implementing this :+1: :100:

**Comment by SConaway** [comment]
Glad it worked!
