### ISSUE TITLE
Double advancement announcement

### ISSUE THREAD

**Issue by polypixeldev** [hackclub/HCCore#157]
When a player gets one of the custom advancements that are added to HCCore, they are announced in chat twice:
![image](https://user-images.githubusercontent.com/79737178/223589439-78bc6800-b1e1-4e61-b372-e6b455c954df.png)

**Comment by the456gamer** [comment]
it didnt with the diamond ones?

**Comment by polypixeldev** [comment]
Issue with my testing server, no issue in HCCore
