### ISSUE TITLE
/msg command suggests nickname instead of actual username

### ISSUE THREAD

**Issue by lukec11** [hackclub/HCCore#42]
when attempting to contact someone using `/w` (or `/msg`), you must use their original username, rather than the custom nickname. The original names do not populate, making this more dificult.

**Comment by ifvictr** [comment]
This happens because we’ve modified the packets to send the player nicknames instead of the actual username for the custom nametags. Looks like we’ll need to override the default command with a custom one that suggests the original usernames on tab-complete.

**Comment by nzeng8** [comment]
I think this would be a problem in the future, because what if two people have the same nickname?  How would you differentiate between the two players?

**Comment by lukec11** [comment]
Even if this was the case, it would still be better than the current problem (that is, the nickname is autocompleted but won't send). 

I think the ideal solution is for people to differentiate Nicknames - or if possible, make `/msg` show name colors from the chat as well.

**Comment by the456gamer** [comment]
![image](https://user-images.githubusercontent.com/42748092/224426029-214b0853-47af-4319-aeba-773d138f38b0.png)
completes with original usernames, cannot reproduce
