### ISSUE TITLE
Chat sharing with #minecraft-chat

### ISSUE THREAD

**Issue by rfblock** [hackclub/HCCore#45]
A simple solution to this would to be
Setup an interface server, minecraft front, and slack front
Slack front is a bot that takes any messages (not from itself) and sends it to the interface
Minecraft front just takes any messages from (not sent from itself) and sends it to the interface
The interface server sends these messages to the other respective front and these fronts display the message in-game or in the channel

**Comment by nice6599** [comment]
so we would get slack messages in minecraft? and on slack we would get messages from the minecraft server? I feel that most if not all people on the server have slack. while it would be cool to have a way to interface with the server chat from outside of minecraft i don't know that slack is the best way to do this

**Comment by ifvictr** [comment]
Yeah, it's just a bridge to a single channel. The whole community is based on Slack, so it'd be an oddity for you _not_ to have a Slack account.

**Comment by eankeen** [comment]
yes agree on overall view, should we use our existing Steve bot for this or create a new one? if new one i'm thinking we can create a simple go front, but i don't really care. as for the message distribution layer, i'm thinking we can channel message data via protobuf encoded grpc's

**Comment by alx-alexpark** [comment]
Implemented on discord server, but might be ported to slack one day
