### ISSUE TITLE
Share locations with other players

### ISSUE THREAD

**Issue by wei2gao** [hackclub/HCCore#69]
I saw the TODO in the LocCommand code for location sharing.

**Comment by wei2gao** [comment]
I can look at this as well. I have some code written for this but I have no idea how I'm going to test a feature that needs two players.

Will this feature save the location into the recipient's list of locations or just tell them the location in chat?

**Comment by ifvictr** [comment]
You can use ngrok to expose the server and post the address in #minecraft to get folks to help test. `/loc share` should make a copy of the player's location and save it into the target player's list with a name in the format of `<player>:<location name>`.

**Comment by wei2gao** [comment]
Suppose we want to share a location called `foo` with a recipient, but we already sent `foo` to them. Should we save it as `<player>:foo2` or just fail?
