### ISSUE TITLE
Add /loc rename

### ISSUE THREAD

**Issue by ifvictr** [hackclub/HCCore#80]
Syntax: `/loc rename <current name> <new name>`

It should autosuggest current names.

**Comment by nice6599** [comment]
small problem. since allowing spaces there is no way to differentiate between two different locations and 1 location.

**Comment by nice6599** [comment]
the solution is to remove spaces and just require people to put dashes in if they want spaces

**Comment by ifvictr** [comment]
Yeah, both parameters should require underscores.

**Comment by nice6599** [comment]
okay it will be two pr's then

**Comment by ifvictr** [comment]
There’s no need for two PRs? They’re still part of the subcommand.

**Comment by nice6599** [comment]
I figured out a way around it
